'use client';
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, CheckCircle } from 'lucide-react';
import { useLanguage } from '@/lib/LanguageContext';
import styles from './ProductCards.module.css';

interface ProductCard {
  name: string;
  tagline: string;
  taglineEn: string;
  description: string;
  descriptionEn: string;
  fullDescription: string;
  fullDescriptionEn: string;
  features: string[];
  featuresEn: string[];
  price: string;
  icon: string;
  color: string;
  compat: string[];
}

const productCardsData: ProductCard[] = [
  {
    name: 'AuditSphere',
    tagline: 'Audit SAP en un clic',
    taglineEn: 'SAP audit in one click',
    icon: '🔍', color: '#00d4ff',
    price: '6 000 € / environnement productif',
    compat: ['SAP ECC', 'S/4HANA'],
    description: "Add-on SAP transportable centralisant 30+ contrôles d'audit automatiques. Dashboard exécutif avec score de risque global.",
    descriptionEn: "Transportable SAP add-on centralizing 30+ automatic audit controls. Executive dashboard with global risk score.",
    fullDescription: "AuditSphere est un add-on SAP 100% transportable qui centralise plus de 30 contrôles d'audit automatiques couvrant les domaines Sécurité, Finance (FI), Gestion des matériaux (MM), Ventes (SD) et la couche Technique. Il génère un score de risque global avec un dashboard exécutif clair, exportable en Excel et PDF.",
    fullDescriptionEn: "AuditSphere is a 100% transportable SAP add-on that centralizes over 30 automatic audit controls covering Security, Finance (FI), Materials Management (MM), Sales (SD) and the Technical layer. It generates a global risk score with a clear executive dashboard, exportable to Excel and PDF.",
    features: ['30+ contrôles automatiques (Sécurité, FI, MM, SD)', 'Score de risque global avec dashboard exécutif', 'Export Excel & PDF intégré', 'Compatible SAP ECC & S/4HANA', 'Transportable — sans infrastructure tierce', 'Rapport synthétique pour le COMEX'],
    featuresEn: ['30+ automatic controls (Security, FI, MM, SD)', 'Global risk score with executive dashboard', 'Integrated Excel & PDF export', 'Compatible with SAP ECC & S/4HANA', 'Transportable — no third-party infrastructure', 'Summary report for C-suite'],
  },
  {
    name: 'Smart Sight',
    tagline: 'Prévisions IA intégrées dans SAP',
    taglineEn: 'AI forecasting integrated in SAP',
    icon: '📈', color: '#4f8ef7',
    price: '1 000 € / mois',
    compat: ['SAP ECC', 'S/4HANA', 'SAP Fiori'],
    description: 'Smart Sight transforme vos KPI existants en prévisions automatiques directement dans SAP.',
    descriptionEn: 'Smart Sight transforms your existing KPIs into automatic forecasts directly in SAP.',
    fullDescription: "Smart Sight est un studio de prévision intégré directement dans vos systèmes SAP. Il transforme vos KPI existants en prévisions automatiques grâce à des algorithmes sans nécessiter de data scientist. Les utilisateurs métier peuvent configurer leurs prévisions et simuler des scénarios directement depuis leur interface SAP habituelle.",
    fullDescriptionEn: "Smart Sight is a forecasting studio integrated directly into your SAP systems. It transforms your existing KPIs into automatic forecasts using algorithms without requiring a data scientist. Business users can configure their forecasts and simulate scenarios directly from their usual SAP interface.",
    features: ['Prévision automatique sur 6 mois glissants', 'Simulation de scénarios what-if', 'Compatible SAP ECC & S/4HANA', 'Zéro data scientist requis', 'Interface native SAP Fiori'],
    featuresEn: ['Automatic 6-month rolling forecast', 'What-if scenario simulation', 'Compatible with SAP ECC & S/4HANA', 'Zero data scientist required', 'Native SAP Fiori interface'],
  },
  {
    name: 'Clean Core',
    tagline: 'Gouvernance des fichiers SAP enterprise',
    taglineEn: 'SAP enterprise file governance',
    icon: '🗂️', color: '#a855f7',
    price: '500 € / mois',
    compat: ['SAP ECC', 'S/4HANA'],
    description: 'Solution de nettoyage et gouvernance des fichiers liés aux interfaces SAP. Multi-SID, archivage automatique et dashboard de suivi.',
    descriptionEn: 'Cleaning and governance solution for SAP interface files. Multi-SID, automatic archiving and monitoring dashboard.',
    fullDescription: "Clean Core est une solution de gouvernance des fichiers d'interfaces SAP conçue pour les environnements multi-systèmes. Elle automatise le nettoyage, l'archivage et le monitoring des fichiers générés par les interfaces SAP. Le dashboard ALV avancé offre une visibilité complète sur l'état de chaque répertoire fichier par système.",
    fullDescriptionEn: "Clean Core is a SAP interface file governance solution designed for multi-system environments. It automates the cleaning, archiving and monitoring of files generated by SAP interfaces. The advanced ALV dashboard offers complete visibility on the status of each file directory per system.",
    features: ['Gouvernance multi-landscape (Multi-SID)', 'Archivage automatique avec règles personnalisables', 'Dashboard ALV avancé avec reporting complet', 'Templates de planification de jobs SAP', 'Audit trail complet des opérations'],
    featuresEn: ['Multi-landscape governance (Multi-SID)', 'Automatic archiving with customizable rules', 'Advanced ALV dashboard with full reporting', 'SAP job scheduling templates', 'Complete operations audit trail'],
  },
];

function ProductModal({ product, onClose, isFr }: { product: ProductCard; onClose: () => void; isFr: boolean }) {
  const features = isFr ? product.features : product.featuresEn;
  return (
    <AnimatePresence>
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
        onClick={onClose}
        style={{ position: 'fixed', inset: 0, zIndex: 1000, background: 'rgba(8,13,26,0.9)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'flex-end', justifyContent: 'center' }}>
        <motion.div
          initial={{ opacity: 0, y: '100%' }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: '100%' }}
          transition={{ duration: 0.35, ease: [0.32, 0.72, 0, 1] }}
          onClick={e => e.stopPropagation()}
          style={{ background: '#0f1c2e', border: `1px solid ${product.color}44`, borderRadius: '20px 20px 0 0', width: '100%', maxWidth: '680px', maxHeight: '92vh', overflowY: 'auto', position: 'relative' }}>
          <div style={{ width: '3rem', height: '4px', background: 'rgba(255,255,255,0.2)', borderRadius: '9999px', margin: '0.75rem auto 0' }} />
          <div style={{ height: '4px', background: `linear-gradient(90deg,${product.color},#4f8ef7)`, marginTop: '0.75rem' }} />
          <button onClick={onClose}
            style={{ position: 'absolute', top: '1.25rem', right: '1.25rem', width: '2rem', height: '2rem', borderRadius: '50%', background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}>
            <X style={{ width: '1rem', height: '1rem', color: '#8ba3c7' }} />
          </button>
          <div style={{ padding: '1.5rem 1.5rem 2.5rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.875rem', marginBottom: '1.25rem' }}>
              <div style={{ width: '3rem', height: '3rem', borderRadius: '12px', background: `${product.color}18`, border: `1px solid ${product.color}35`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.5rem', flexShrink: 0 }}>{product.icon}</div>
              <div>
                <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#ffffff', margin: 0 }}>{product.name}</h2>
                <p style={{ fontSize: '0.8rem', color: product.color, fontStyle: 'italic', margin: '0.15rem 0 0' }}>{isFr ? product.tagline : product.taglineEn}</p>
              </div>
            </div>
            <div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap', marginBottom: '1.25rem' }}>
              {product.compat.map(env => (
                <span key={env} style={{ fontSize: '0.7rem', fontWeight: 600, padding: '0.2rem 0.6rem', borderRadius: '9999px', background: `${product.color}18`, border: `1px solid ${product.color}35`, color: product.color }}>{env}</span>
              ))}
            </div>
            <div style={{ height: '1px', background: 'rgba(0,212,255,0.1)', marginBottom: '1.25rem' }} />
            <p style={{ fontSize: '0.875rem', color: '#c8d8ee', lineHeight: 1.75, marginBottom: '1.5rem' }}>
              {isFr ? product.fullDescription : product.fullDescriptionEn}
            </p>
            <h3 style={{ fontSize: '0.8rem', fontWeight: 700, color: '#ffffff', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '0.875rem' }}>
              {isFr ? 'Fonctionnalités clés' : 'Key features'}
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginBottom: '1.75rem' }}>
              {features.map((f, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '0.5rem' }}>
                  <CheckCircle style={{ width: '0.875rem', height: '0.875rem', color: product.color, flexShrink: 0, marginTop: '0.15rem' }} />
                  <span style={{ fontSize: '0.85rem', color: '#ffffff', lineHeight: 1.5 }}>{f}</span>
                </div>
              ))}
            </div>
            <div style={{ paddingTop: '1.25rem', borderTop: '1px solid rgba(0,212,255,0.1)' }}>
              <p style={{ fontSize: '0.72rem', color: '#8ba3c7', margin: '0 0 0.25rem' }}>{isFr ? 'À partir de' : 'Starting from'}</p>
              <p style={{ fontSize: '1.15rem', fontWeight: 800, color: product.color, margin: '0 0 1.25rem' }}>{product.price}</p>
              <div style={{ display: 'flex', gap: '0.75rem' }}>
                <button onClick={onClose}
                  style={{ flex: 1, padding: '0.75rem', borderRadius: '10px', border: '1px solid rgba(0,212,255,0.3)', background: 'transparent', color: '#8ba3c7', fontSize: '0.875rem', cursor: 'pointer' }}>
                  {isFr ? 'Fermer' : 'Close'}
                </button>
                <a href="/contact" style={{ flex: 2, textDecoration: 'none' }}>
                  <button style={{ width: '100%', padding: '0.75rem', borderRadius: '10px', border: 'none', background: `linear-gradient(135deg,${product.color},#4f8ef7)`, color: '#080d1a', fontSize: '0.875rem', fontWeight: 700, cursor: 'pointer' }}>
                    {isFr ? 'Demander une démo →' : 'Request a demo →'}
                  </button>
                </a>
              </div>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

function FlipCard({ product, index, onOpenModal, isMobile, isFr }: { product: ProductCard; index: number; onOpenModal: () => void; isMobile: boolean; isFr: boolean }) {
  const [flipped, setFlipped] = useState(false);
  return (
    <div className={styles.glowWrapper} style={{ animationDelay: `${index * 0.15}s` }}
      onMouseEnter={() => !isMobile && setFlipped(true)}
      onMouseLeave={() => !isMobile && setFlipped(false)}
      onClick={() => { if (isMobile) { if (flipped) onOpenModal(); else setFlipped(true); } }}>
      <div style={{ width: '100%', height: '100%', perspective: '1000px', borderRadius: '14px' }}>
        <div className={`${styles.cardInner} ${flipped ? styles.flipped : ''}`}>
          <div className={`${styles.cardFace} ${styles.cardFront}`}>
            <span className={styles.icon}>{product.icon}</span>
            <h3 className={styles.productName}>{product.name}</h3>
            <p className={styles.tagline}>{isFr ? product.tagline : product.taglineEn}</p>
            <span className={styles.hintText}>{isMobile ? (isFr ? 'Toucher pour découvrir →' : 'Tap to discover →') : (isFr ? 'Survoler pour découvrir →' : 'Hover to discover →')}</span>
          </div>
          <div className={`${styles.cardFace} ${styles.cardBack}`}>
            <div className={styles.backContent}>
              <h4 className={styles.backTitle}>{product.name}</h4>
              <p className={styles.description}>{isFr ? product.description : product.descriptionEn}</p>
              <ul className={styles.featuresList}>
                {(isFr ? product.features : product.featuresEn).slice(0, 4).map((f, i) => (
                  <li key={i} className={styles.featureItem}>
                    <span className={styles.featureBullet}>✦</span><span>{f}</span>
                  </li>
                ))}
              </ul>
              <div className={styles.priceBadge}>{product.price}</div>
              <button className={styles.ctaButton} onClick={e => { e.stopPropagation(); onOpenModal(); }}>
                {isFr ? 'En savoir plus →' : 'Learn more →'}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ProductCards() {
  const { language } = useLanguage();
  const isFr = language === 'fr';
  const [selectedProduct, setSelectedProduct] = useState<ProductCard | null>(null);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const check = () => setIsMobile(window.innerWidth < 768);
    check();
    window.addEventListener('resize', check);
    return () => window.removeEventListener('resize', check);
  }, []);

  return (
    <>
      <section style={{ minHeight: '100vh', padding: '5rem 1rem 4rem', position: 'relative', zIndex: 1 }}>
        <div style={{ maxWidth: '1280px', margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
            <h2 style={{ fontSize: 'clamp(1.75rem,5vw,3rem)', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '1rem' }}>
              {isFr ? 'Nos Solutions SAP' : 'Our SAP Solutions'}
            </h2>
            <p style={{ fontSize: 'clamp(0.9rem,2vw,1.125rem)', color: 'var(--text-secondary)', maxWidth: '42rem', margin: '0 auto', padding: '0 1rem' }}>
              {isFr ? 'Découvrez nos solutions innovantes pour optimiser vos opérations SAP' : 'Discover our innovative solutions to optimize your SAP operations'}
            </p>
            {isMobile && <p style={{ fontSize: '0.8rem', color: '#8ba3c7', marginTop: '0.5rem', opacity: 0.7 }}>
              {isFr ? 'Touchez une carte pour découvrir, puis à nouveau pour en savoir plus' : 'Tap a card to discover, then again to learn more'}
            </p>}
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(auto-fit,minmax(280px,1fr))', gap: '1.5rem' }}>
            {productCardsData.map((product, index) => (
              <FlipCard key={index} product={product} index={index} isMobile={isMobile} isFr={isFr} onOpenModal={() => setSelectedProduct(product)} />
            ))}
          </div>
        </div>
      </section>
      {selectedProduct && <ProductModal product={selectedProduct} isFr={isFr} onClose={() => setSelectedProduct(null)} />}
    </>
  );
}